### ISSUE TITLE
Hidden columns are confusing

### ISSUE THREAD

**Issue by bbbales2** [jgabry/posterior#69]
When I'm doing diagnostic stuff I like to be able to separate chains.

So them I'm writing with the hidden `.chain` and `.iteration` variables:

```
fit1$sampler_diagnostics() %>%
  as_draws_df() %>%
  ggplot(aes()) +
  geom_point(aes(.iteration, n_leapfrog__)) +
  facet_grid(.chain ~ .)
```

I guess now that I know they're there it's not a problem, but it's easier to know that all the columns in my dataframe are visible.

Why are these hidden?

**Comment by paul-buerkner** [comment]
I thought it is better to only show actual variables by default, this this can be changed using the `meta_columns` argument of the print method. The question is whether this argument should be TRUE or FALSE by default and I am happy to discuss the pros and cons of these options.

**Comment by bbbales2** [comment]
Is there any way to indicate the hidden columns print of the table? Like for example in the comments at the top of the print:

```
# A draws_df: 1000 iterations, 4 chains, and 9 variables (hidden columns .chains and .iterations)
```

I don't know if that's less confusing or likely to get people on the right track. I think I found out about these secret columns watching Jonah.

It does seem convenient to hide them. In what is presumably the most important use case (interpreting posterior samples) exposing `chain` and `iterations` would just mean everyone does a `select(-chain, -iterations)` as step-1, which doesn't seem ideal.

**Comment by paul-buerkner** [comment]
That sounds like a good idea. I will add a note to the print output in that regard.

**Comment by paul-buerkner** [comment]
How about:

```R
x <- as_draws_df(example_draws())
print(x)
# A draws_df: 100 iterations, 4 chains, and 10 variables
     mu tau theta[1] theta[2] theta[3] theta[4] theta[5] theta[6]
1  2.01 2.8     3.96    0.271    -0.74      2.1    0.923      1.7
2  1.46 7.0     0.12   -0.069     0.95      7.3   -0.062     11.3
3  5.81 9.7    21.25   14.931     1.83      1.4    0.531      7.2
4  6.85 4.8    14.70    8.586     2.67      4.4    4.758      8.1
5  1.81 2.8     5.96    1.156     3.11      2.0    0.769      4.7
6  3.84 4.1     5.76    9.909    -1.00      5.3    5.889     -1.7
7  5.47 4.0     4.03    4.151    10.15      6.6    3.741     -2.2
8  1.20 1.5    -0.28    1.846     0.47      4.3    1.467      3.3
9  0.15 3.9     1.81    0.661     0.86      4.5   -1.025      1.1
10 7.17 1.8     6.08    8.102     7.68      5.6    7.106      8.5
# ... with 390 more draws, and 2 more variables
# ... hidden meta-columns {'.chain', '.iteration', '.draw'}
```

**Comment by bbbales2** [comment]
I like it. That is where you look for columns that don't get printed cause of space requirements, so I think that does give people a reasonable chance of figuring this for free.

**Comment by paul-buerkner** [comment]
Good. I pushed the change already and will close this issue.

**Comment by ASKurz** [comment]
When using the `as_draws_df()` method, what is the simplest way to include the hidden meta-columns along with the other columns?

```{r}
library(tidyverse)
library(posterior)

example_draws() %>% 
  as_draws_df()
```

**Comment by mjskay** [comment]
Do you mean for printing purposes? Perhaps something like this:

```r
example_draws() %>% 
    as_draws_df() %>%
    print(reserved = TRUE)
```

**Comment by ASKurz** [comment]
Also, how does one work with the reserved variables? Say, for example, I just wanted to use one of them within `count()`. Both of these fail.

```
example_draws() %>% 
  as_draws_df() %>%
  print(reserved = TRUE) %>% 
  count(.chain)

example_draws() %>% 
  as_draws_df() %>%
  count(.chain)
```

**Comment by mjskay** [comment]
Hmm interesting. This appears to come up with `count()` and not other dplyr functions (at least I tried a couple and they were fine -- only count exhibited this issue). E.g. if you try using `mutate()` or `summarise()` they should work fine.

What is happening is that `count()` is summarizing the draws data frame into a format that doesn't match the draws format (specifically `count(.chain)` will mean there are no `.iteration` or `.draw` columns). That would all be fine except that it then re-applies the attributes of the input data frame to its output, which includes the class --- so you end up with a data frame that does have your desired result but which has the `"draws_df"` class applied to it.

You can see this because the result is actually fine (does not error) until you try to print it; and if you convert it to a data frame or tibble it gives the expected output:

```r
> counts = example_draws() %>% 
+     as_draws_df() %>%
+     count(.chain)
> counts
# A draws_df: 0 iterations, 4 chains, and 1 variables
Error: Can't subset columns that don't exist.
x Columns `.iteration` and `.draw` don't exist.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
Unknown or uninitialised column: `.iteration`. 
> as_tibble(counts)
# A tibble: 4 x 2
  .chain     n
   <int> <int>
1      1   100
2      2   100
3      3   100
4      4   100
```

So, one workaround is to convert to a tibble somewhere in your pipe (it doesn't really matter where) if your final output will not be a `"draws_df"`.

Reading more about this on the dplyr side, probably the right thing to do is for us to implement `dplyr::dplyr_reconstruct()` for the `"draws_df"` class in a similar way to `[.draws_df` so that it drops the class if required columns are removed (possibly with a warning like `[.draws_df` does, or maybe not?). We should be able to do this while keeping `dplyr` in suggests. See [here](https://dplyr.tidyverse.org/reference/dplyr_extending.html). Opening an issue for this...

Re: documentation, the printing issue is obliquely mentioned in the docs for `print.as_draws_df` if you squint at the `reserved` parameter. Probably there should just be an example there.

**Comment by ASKurz** [comment]
Hey @mjskay, I'm not sure if this is exactly related, but I just ran into a similar problem when trying to use `dplyr::sample_n()` and `dplyr::slice_sample()`. Both instances return a bunch of `NA`. My current version of **posterior** is 1.1.0.900.

```{r}
example_draws() %>%
  as_draws_df() %>% 
  sample_n(size = 3)

example_draws() %>%
  as_draws_df() %>% 
  slice_sample(n = 3)
```

**Comment by mjskay** [comment]
That... is an interesting bug! Not sure what's going on there, but I'll open a separate issue for it.
