### ISSUE TITLE
selecting non-scalar parameters by name

### ISSUE THREAD

**Issue by jgabry** [jgabry/posterior#71]
This came up in a cmdstanr PR: https://github.com/stan-dev/cmdstanr/pull/164#issuecomment-639817098

It would be really nice if `subset_draws(..., variable="theta")` selected all elements of a vector/matrix parameter theta. Currently you need to provide a vector explicitly naming all elements of theta or use the regex option with `"theta\\["` or something like that.

Thoughts? Did we debate this somewhere already?

**Comment by jgabry** [comment]
This could be an option that defaults to off but can be turned on.

**Comment by MansMeg** [comment]
One alternative could be to use the tidyselect framework, that it would be easier for more special selections. But maybe this is a very specific request?

**Comment by paul-buerkner** [comment]
I like the idea! We should definitely have a flag turning this off or on. I argue we should probably turn defaulting it to TRUE, because it creates little ambiguity. If `theta` is a scalar parameter, it is extracted. If, alternative, `theta` has a dimension (via `[...]`) all elements will be extracted. The only potential ambiguity comes when there is both a scalar `theta` and a `theta` with dimension but this should be rare and we can just extract both my default. I will implement this feature.

With regard to tidyselect, I remember that we had discussed that at some point but I cannot remember where or what the conclusions were. Does anybody remember?

**Comment by paul-buerkner** [comment]
I have just added this feature in the form of the `scalar` argument (name subject to discussion):

```R
x <- as_draws_df(example_draws())
x_sub <- subset_draws(x, variable = "theta", scalar = FALSE)
variables(x_sub)
> [1] "theta[1]" "theta[2]" "theta[3]" "theta[4]" "theta[5]" "theta[6]" "theta[7]" "theta[8]"

x_sub <- subset_draws(x, variable = "theta[1]", scalar = FALSE)
variables(x_sub)
> [1] "theta[1]"

x_sub <- subset_draws(x, variable = "theta", scalar = TRUE)
> Error: The following variables are missing in the draws object: {'theta'} 
``` 

Points to discuss:

- Is `scalar` a good argument name? 
- What should be the default in `subset_draws`? (current is `FALSE`)
- Is the doc of `scalar` understandable?
- Should we use `scalar` in `rename_variables` as well?
- If yes to the former, what should be the default there?

**Comment by MansMeg** [comment]
Some short thoughts:
Semantically the argument name makes me think of a scalar value. Ie I start to think that this would return a single value rather than a vector of samples for a single parameter. I dont have any good other suggestions but maybe ’scalar_name’ or ’scalar_parameter’ to signal that it will not return a scalar.

I think it should be default true. The reason is that if I want a single value, I would write that directly, like theta[1]. If I write ’theta’ it is reasonable to assume that I would want them all (and not that it is an error from the users perspective).

**Comment by paul-buerkner** [comment]
So @MansMeg you suggest the whole `theta` vector should be extractable by default, right? This is what I argue as well, just that for me, this is realized via `scalar = FALSE`, since you then not only extract scalar parameters. Based on your comments, it seems you read `scalar` the other way round. If that is the case, this is definitely an argument against calling the argument `scalar`.

**Comment by MansMeg** [comment]
Yes. I read it the other way around (I think the confusion comes from ”it is a scalar” vs ”should return a scalar”). Scalar is a little ambiguous. We should probably find a more explicit name. 

Just a thought. Is there any problem of having this as default without an argument? I guess if I want I can always specify individual parameters as theta[1] and I assume stan syntax do not allow [] in variable names?

**Comment by paul-buerkner** [comment]
I agree we should find another name. I would also be ok with not having this as an argument, but I think it would be safer to have an argument to turn this of if required, even if only for cases we didn't think of at the moment.

We could also call the argument, for example, `require_index` indicating whether the variable index need to be provided for selecting the variable (defaulting to FALSE). What would you think of that name?

**Comment by jgabry** [comment]
Thanks for implementing this @paul-buerkner! 

> Just a thought. Is there any problem of having this as default without an argument? I guess if I want I can always specify individual parameters as theta[1] and I assume stan syntax do not allow [] in variable names?

@MansMeg I can't think of any problem but I think I agree with @paul-buerkner that it would be safer to have an argument just in case. 

> We could also call the argument, for example, `require_index` indicating whether the variable index need to be provided for selecting the variable (defaulting to FALSE). What would you think of that name?

I like `require_index` better than `scalar` (i see why @MansMeg interpreted it differently). Another possibility that I kind of like is `scalar_only` (defaulting to `FALSE`), which would indicate that names in `variable` refer to scalars only (including individual elements of vectors/matrix).

**Comment by paul-buerkner** [comment]
A drawback would be to have to maintain such an argument although nobody may need it. So we could alternatively keep the `scalar_only` argument internal and only expose it once someone complains?

**Comment by jgabry** [comment]
That's true. I'm ok with waiting to expose the argument.

**Comment by paul-buerkner** [comment]
Made the discussed changes. Both `subset_draws` and `rename_variables` now handle non-scalar variables and `scalar_only` remains internal for the time being.

Thank you @MansMeg for @jgabry for your input. 

I think all discussion points have been resolved so I am closing this issue.

**Comment by jgabry** [comment]
Thanks @paul-buerkner !

**Comment by MansMeg** [comment]
Yes, great work @paul-buerkner !
